### ISSUE TITLE
Clicking on Video.js control bar stops hot keys from working

### ISSUE THREAD

**Issue by DongDanBam** [sweetberry/videojs-shuttle-controls#1]
In the example at https://sweetberry.github.io/videojs-shuttle-controls/

within the video.js video player when you click on the controlbar speed control (or) the play/pause button , the hot keys no longer work.

I am also seeing this same issue in my independent tests.

What do you think?

**Comment by sweetberry** [comment]
I'm sorry.
I missed this message.

In my environment, I could not reproduce the situation you showed.

If you could let me know more information about your environment, it would help me.
